version: "3.2"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: mitc:02.2021
    command: bin/rails server --port 3001 --binding 0.0.0.0
    ports:
      - "3001:3001"
    volumes:
      - .:/mitc
      - type: tmpfs
        target: /mitc/tmp/pids/
